version: "3.1"
services:
  # mongodb://localhost:27017
  mongodb:
    image: "mongo:6.0.2"
    restart: always
    environment:
      MONGO_INITDB_DATABASE: parcial3
    ports:
      - "27017:27017"
  # http://localhost:8001
  backend:
    build: backend
    environment:
      mongo_url: "mongodb://mongodb:27017"
    env_file:
      - backend/.env
    ports:
      - "8001:8000"
    
