/* tslint:disable */
/* eslint-disable */
/**
 * Tercer Parcial - API REST. Ingeniería Web
 * José Luis Bueno Pachón.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Usuario
 */
export interface Usuario {
    /**
     * 
     * @type {string}
     * @memberof Usuario
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof Usuario
     */
    nombre: string;
    /**
     * 
     * @type {string}
     * @memberof Usuario
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof Usuario
     */
    apellidos: string;
    /**
     * 
     * @type {string}
     * @memberof Usuario
     */
    direccion: string;
    /**
     * 
     * @type {number}
     * @memberof Usuario
     */
    latitude: number;
    /**
     * 
     * @type {number}
     * @memberof Usuario
     */
    longitude: number;
    /**
     * 
     * @type {string}
     * @memberof Usuario
     */
    foto: string;
}

/**
 * Check if a given object implements the Usuario interface.
 */
export function instanceOfUsuario(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "nombre" in value;
    isInstance = isInstance && "email" in value;
    isInstance = isInstance && "apellidos" in value;
    isInstance = isInstance && "direccion" in value;
    isInstance = isInstance && "latitude" in value;
    isInstance = isInstance && "longitude" in value;
    isInstance = isInstance && "foto" in value;

    return isInstance;
}

export function UsuarioFromJSON(json: any): Usuario {
    return UsuarioFromJSONTyped(json, false);
}

export function UsuarioFromJSONTyped(json: any, ignoreDiscriminator: boolean): Usuario {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, '_id') ? undefined : json['_id'],
        'nombre': json['nombre'],
        'email': json['email'],
        'apellidos': json['apellidos'],
        'direccion': json['direccion'],
        'latitude': json['latitude'],
        'longitude': json['longitude'],
        'foto': json['foto'],
    };
}

export function UsuarioToJSON(value?: Usuario | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        '_id': value.id,
        'nombre': value.nombre,
        'email': value.email,
        'apellidos': value.apellidos,
        'direccion': value.direccion,
        'latitude': value.latitude,
        'longitude': value.longitude,
        'foto': value.foto,
    };
}

